config/routes.rb
Juventude::Application.routes.draw do

  resources :dados do
    collection do
      get :fontes
    end
  end

  resources :temas
  resources :pnads,      :path => :pnad
  resources :agendas, :path => :agenda
  resources :indicadors, :path => :indicadores

  match '/:id' => "shortener/shortened_urls#show"

  root :to => 'dados#index'

end

app/models/tema.rb
class Tema < ActiveRecord::Base
  extend FriendlyId
  friendly_id :titulo, use: :slugged

  has_many :temas_indicadors, :dependent => :destroy
  has_many :indicadors, :through => :temas_indicadors

  # accepts_nested_attributes_for :indicadors

  attr_accessible :titulo, :imagem

  has_attached_file :imagem, :styles => { :medium => "250x250>", :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :imagem, :content_type => /\Aimage\/.*\Z/
end

app/controllers/temas_controller.rb
class TemasController < ApplicationController
  # GET /temas/dados/1
  # GET /temas/dados/1.json
  def dados
    @dados = []

    tema = Tema.find(params[:id])

    @dados = getDadosByTema(Tema.find(params[:tema]))

    respond_to do |format|
      format.js
    end
  end



  # GET /temas
  # GET /temas.json
  def index
    @temas = Tema.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @temas }
    end
  end

  # GET /temas/1
  # GET /temas/1.json
  def show
    @tema = Tema.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tema }
    end
  end
	
  # GET /temas/new
  # GET /temas/new.json
  def new
    @tema = Tema.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tema }
    end
  end

  # GET /temas/1/edit
  def edit
    @tema = Tema.find(params[:id])
  end

  # POST /temas
  # POST /temas.json
  def create
    @tema = Tema.new(params[:tema])

    respond_to do |format|
      if @tema.save
        format.html { redirect_to @tema, notice: 'Tema foi Criado com sucesso.' }
        format.json { render json: @tema, status: :created, location: @tema }
      else
        format.html { render action: "new" }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /temas/1
  # PUT /temas/1.json
  def update
    @tema = Tema.find(params[:id])

    respond_to do |format|
      if @tema.update_attributes(params[:tema])
        format.html { redirect_to @tema, notice: 'Tema foi Atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temas/1
  # DELETE /temas/1.json
  def destroy
    @tema = Tema.find(params[:id])
    @tema.destroy

    respond_to do |format|
      format.html { redirect_to temas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/temas_helper.rb
module TemasHelper
end

app/views/temas/_form.html.erb
<%= form_for(@tema, :html => { :multipart => true } ) do |f| %>
  <% if @tema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tema.errors.count, "error") %> prohibited this tema from being saved:</h2>

      <ul>
      <% @tema.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Título" %><br />
    <%= f.text_field :titulo %>
  </div>

  <div class="field">
    <%= f.label "Imagem" %><br />
    <%= f.file_field :imagem %>
  </div>

  <div class="actions">
    <%= f.submit "Enviar" %>
  </div>
<% end %>

app/views/temas/edit.html.erb
<br/>

<center>
	<%= link_to 'Mostrar', @tema %> |
	<%= link_to 'Voltar', temas_path %>
</center>

<br/>

<%= render 'form' %>

app/views/temas/index.html.erb
<br/>
<center>
    <%= link_to 'Novo Tema', new_tema_path %> |
    <%= link_to 'Administrar Indicador', indicadors_path %> |
    <%= link_to 'Ver Dados', dados_path %>

    <br /><br />
    <% if ! @temas.empty? %>
      <table class="table-dados">
        <tr id="table-header">
          <th></th>
          <th>Indicadors</th>
          <th></th>
          <th></th>
        </tr>

      <% @temas.each do |tema| %>
        <tr class="table-<%= cycle('even', 'odd') -%>">
          <td><%= link_to image_tag(tema.imagem.url(:thumb)), tema %> <br /><b><%= tema.titulo%></b></td>
          <td><%= tema.indicadors.count %></td>
          <td><%= link_to 'Editar', edit_tema_path(tema) %></td>
          <td><%= link_to 'Apagar', tema, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
        </tr>
      <% end %>
      </table>
    <% else %>
        <br />
        <h3>Nenhum Tema Encontrado.</h3>
    <% end %>
</center>

app/views/temas/new.html.erb
<br/>

<center>
	<%= link_to 'Voltar', temas_path %>
</center>

<br/>

<%= render 'form' %>

app/views/temas/show.html.erb
<br />

<center>
  <%= link_to 'Editar', edit_tema_path(@tema) %> |
  <%= link_to 'Voltar', temas_path %>

  <p id="notice"><%= notice %></p>

<p>
  <%= image_tag @tema.imagem.url(:thumb) %>
</p>

<p>
  <b><%= @tema.titulo %></b>
</p>

	<p>
	  <b>Indicadors deste Tema:</b> <br />
          <% if @tema.indicadors.count > 0 %>
            <% @tema.indicadors.each do |indicador| %>
              <%= link_to Pnad::OBJETIVO.index(indicador.objetivo), indicador %><br />
	    <% end %>
            <br />
            <b><%= link_to 'Adicione/Modifique um Novo Indicador', indicadors_path %> a este Tema.</b>

          <% else %>
            Nenhum Indicador Encontrado. Adicione <%= link_to 'um novo Indicador', new_indicador_path %>
          <% end %>
	</p>
</center>