config/routes.rb
Juventude::Application.routes.draw do

  resources :dados do
    collection do
      get :fontes
    end
  end

  resources :temas
  resources :pnads,      :path => :pnad
  resources :agendas, :path => :agenda
  resources :indicadors, :path => :indicadores

  match '/:id' => "shortener/shortened_urls#show"

  root :to => 'dados#index'

end

app/controllers/dados_controller.rb
class DadosController < ApplicationController
  # GET /dados
  # GET /dados.json
  def index
    @temas = Tema.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @temas }
    end
  end

  # GET /dados/1
  # GET /dados/1.json
  def show
    @dados = []

    @dados = getDadosByTema(Tema.find(params[:tema]))

    respond_to do |format|
      format.js
    end
  end

  def fontes

  end
end

app/helpers/dados_helper.rb
module DadosHelper
end

app/views/dados/_dados.html.erb
<br />
<% if ! dados.empty? %>
  <% dados.each do |value| %>
    <%= pie_chart    value[:data], value[:config] if value[:type] == 'pie'    %>
    <%= bar_chart    value[:data], value[:config] if value[:type] == 'bar'    %>
    <%= line_chart   value[:data], value[:config] if value[:type] == 'line'   %>
    <%= column_chart value[:data], value[:config] if value[:type] == 'column' %>
    <%= area_chart   value[:data], value[:config] if value[:type] == 'area'   %>
  <% end %>

  <% if params[:controller] != 'agendas'%>
    <%= social_share_button_tag(dados[0][:titulo], :url => short_url(dados[0][:url])) %>
  <% end %>

  <br/>
<% else %>
  <br /><br />
  <center>
    <h3>Nenhum Dado Encontrado.</h3>
  </center>
<% end %>

app/views/dados/fontes.html.erb
<br/>

<div class="dados-options">
  <%= link_to "Página Principal", dados_path %>
</div>

<br />

<center>
<% if params[:tema] %>
    <div class="dados-titulo">Bases de dados</div>
      <table class="table-fontes">
          <tr class="tr-fontes">
              <td class="td-fontes"><%= link_to image_tag('PNAD.jpg', width: '220'), pnads_path + "?tema=#{params[:tema]}" %></td>
              <td class="td-fontes"><%= link_to image_tag('participatorio.png'), agendas_path + "?tema=#{params[:tema]}" %></td>
              <td class="td-fontes"><%= image_tag('IBGE.jpg', width: '250') %></td>
          </tr>
      </table>
  </div>

<% else %>
  <br /><br />
  <h2>Nenhum Tema Definido Encontrado.</h2>
<% end %>
</center>
</div>

app/views/dados/index.html.erb
<br/><br/>

<br />

<div id="dados-header">
  Dados Estatísticos
</div>

<div id="dados-body">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mollis justo mauris, eget ornare eros scelerisque at. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ac augue vitae erat dictum tristique ut a velit. Nam rutrum vestibulum sodales. Nam et luctus ipsum. Sed ut tellus at justo dictum pretium. Phasellus ut purus semper, fermentum ipsum vel, placerat est. Morbi id fringilla tellus. Etiam pharetra consectetur placerat.
</div>

  <%#= collection_select(nil, :id, @indicadors, :id, :titulo, {:prompt => "Selecione o Indicador"}, {:id => 'select_indicadors'}) %>
  <%#= collection_select(nil, :id, @temas, :id, :titulo, {:prompt => "Selecione o Tema"}, {:id => 'select_temas'}) %>
  <br />
<div id="dados-geral">
  <div id="dados-temas">
    <center>
    <div class="dados-titulo">Eixos Temáticos</div>
    <% if ! @temas.empty? %>
      <table class="table-temas">
        <% @temas.each_slice(3) do |tema_slice| %>
          <tr class="tr-temas" style="background-color: #fff;">
            <% tema_slice.each do |tema| %>
              <td class="td-temas">
                <%= link_to image_tag(tema.imagem.url(:medium), width: '190', height: '190'), fontes_dados_path + "?tema=#{tema.slug}", :class => 'link_tema', :style => 'background-color: #fff;', :'data-href' => tema.slug %> <br />
                <b><%= tema.titulo%></b>
              </td>
            <% end %>
          </tr>
        <% end %>
      </table>


    <% else %>
        <br />
        <h3>Nenhum Tema Encontrado.</h3>
    <% end %>
    <br/>
    <div class="dados-titulo">Bases de dados</div>
      <table class="table-fontes">
          <tr class="tr-fontes">
              <td class="td-fontes"><%= link_to image_tag('PNAD.jpg', width: '220'), pnads_path %></td>
              <td class="td-fontes"><%= link_to image_tag('participatorio.png'), agendas_path %></td>
              <td class="td-fontes"><%= image_tag('IBGE.jpg', width: '250') %></td>
          </tr>
      </table>
   </div>

    <!--
    <div class="dados-options">
      <%#= link_to "Administrar Temas",   temas_path %> |
      <%#= link_to "Administrar Indicadores", indicadors_path %>
    </div>
    -->
  </div>

  </center>
</div>

app/views/dados/show.js.erb
$('#dados').html("<%= escape_javascript(render(partial: "dados", locals: { dados: @dados })).html_safe %>")