config/routes.rb
Juventude::Application.routes.draw do

  resources :dados do
    collection do
      get :fontes
    end
  end

  resources :temas
  resources :pnads,      :path => :pnad
  resources :agendas, :path => :agenda
  resources :indicadors, :path => :indicadores

  match '/:id' => "shortener/shortened_urls#show"

  root :to => 'dados#index'

end

app/models/indicador.rb
class Indicador < ActiveRecord::Base
  has_many :temas_indicadors, :dependent => :destroy
  has_many :temas, :through => :temas_indicadors

  attr_accessible :objetivo, :fonte, :tema_ids
end

app/controllers/indicadors_controller.rb
class IndicadorsController < ApplicationController
  # GET /indicadors
  # GET /indicadors.json
  def index
    @indicadors = Indicador.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @indicadors }
    end
  end

  # GET /indicadors/1
  # GET /indicadors/1.json
  def show
    @dados = []

    @indicador = Indicador.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @indicador }
    end
  end

  # GET /indicadors/new
  # GET /indicadors/new.json
  def new
    @indicador = Indicador.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @indicador }
    end
  end

  # GET /indicadors/1/edit
  def edit
    @indicador = Indicador.find(params[:id])
  end

  # POST /indicadors
  # POST /indicadors.json
  def create
    @indicador = Indicador.new(params[:indicador])
    @indicador.attributes = {'tema_ids' => []}.merge(params[:indicador] || {})

    respond_to do |format|
      if @indicador.save
        format.html { redirect_to @indicador, notice: 'Indicador foi Criado com sucesso.' }
        format.json { render json: @indicador, status: :created, location: @indicador }
      else
        format.html { render action: "new" }
        format.json { render json: @indicador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /indicadors/1
  # PUT /indicadors/1.json
  def update
    @indicador = Indicador.find(params[:id])
    @indicador.attributes = {'tema_ids' => []}.merge(params[:indicador] || {})

    respond_to do |format|
      if @indicador.update_attributes(params[:indicador])
        format.html { redirect_to @indicador, notice: 'Indicador foi Atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @indicador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indicadors/1
  # DELETE /indicadors/1.json
  def destroy
    @indicador = Indicador.find(params[:id])
    @indicador.destroy

    respond_to do |format|
      format.html { redirect_to indicadors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/indicadors_helper.rb
module IndicadorsHelper
end

app/views/indicadors/_form.html.erb
<%= form_for(@indicador) do |f| %>
  <% if @indicador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@indicador.errors.count, "error") %> prohibited this indicador from being saved:</h2>
      <ul>
      <% @indicador.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Objetivo" %><br />
    <%= f.select :objetivo, Pnad::OBJETIVO.map { |value| [ value[0], value[1] ] } %>
  </div>

  <div class="field">
    <%= f.label "Fonte" %><br />
    <%= f.select :fonte, Pnad::FONTE.map { |value| [ value[0], value[1] ] } %>
  </div>

  <% if Tema.first %>
    <div class="field">
      <%= f.label "Escolha os Temas" %><br /><br />
      <table class="table-temas">
        <% Tema.all.each_slice(3) do |tema_slice| -%>
          <tr>
            <% tema_slice.each do |tema| -%>
              <td>
                <%= image_tag tema.imagem.url(:thumb) %>
                <b><%= label_tag :tema_ids, tema.titulo -%></b>
                <%= check_box_tag :tema_ids, tema.id, @indicador.temas.include?(tema), :name => 'indicador[tema_ids][]' -%>
              </td>
            <% end -%>
          </tr>
        <% end -%>
      </table>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Enviar" %>
  </div>

<% end %>

app/views/indicadors/edit.html.erb
<br/>

<center>
	<%= link_to 'Mostrar', @indicador %> |
	<%= link_to 'Voltar', indicadors_path %>
</center>

<br/>

<%= render 'form' %>

app/views/indicadors/index.html.erb
<br/>
<center>
    <%= link_to 'Novo Indicador', new_indicador_path %> |
    <%= link_to 'Administrar Tema', temas_path %> |
    <%= link_to 'Ver Dados', dados_path %>

    <br /><br />
    <% if ! @indicadors.empty? %>
        <table class="table-dados">
          <tr id="table-header">
            <th>Objetivo</th>
            <th>Fonte</th>
            <th></th>
            <th></th>
          </tr>

        <% @indicadors.each do |indicador| %>
          <tr class="table-<%= cycle('even', 'odd') -%>">
            <td><b><%= link_to Pnad::OBJETIVO.index(indicador.objetivo), indicador %></b></td>
            <td><%= Pnad::FONTE.index(indicador.fonte)%></td>
            <td><%= link_to 'Editar', edit_indicador_path(indicador) %></td>
            <td><%= link_to 'Apagar', indicador, method: :delete, data: { confirm: 'Você tem Certeza?' } %></td>
          </tr>
        <% end %>
        </table>
    <% else %>
        <br />
        <h3>Nenhum Indicador Encontrado.</h3>
    <% end %>
</center>

app/views/indicadors/new.html.erb
<br/>

<center>
	<%= link_to 'Voltar', indicadors_path %>
</center>

<br/>

<%= render 'form' %>

app/views/indicadors/show.html.erb
<br />
<center>
  <%= link_to 'Editar', edit_indicador_path(@indicador) %> |
  <%= link_to 'Voltar', indicadors_path %>

  <p id="notice"><%= notice %></p>
</center>

<p>
  <b>Objetivo:</b>
  <%= Pnad::OBJETIVO.index(@indicador.objetivo) %>
</p>

<p>
  <b>Fonte:</b>
  <%= Pnad::FONTE.index(@indicador.fonte) %>
</p>

<% if ! @indicador.temas.empty? %>
<center>
  <p>
    <b>Temas que este Indicador faz Parte:</b>
      <table class="table-temas">
        <tr>
          <% @indicador.temas.each do |tema| -%>
            <td>
            <%= link_to (image_tag tema.imagem.url(:thumb)), tema %>
            <b><%= label_tag :tema_ids, tema.titulo -%></b>
            </td>
          <% end -%>
        </tr>
      </table>
  </p>
</center>
<% end %>